[package]
name = "lsystem"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24.7"
imageproc = "0.23.0"
rand = "0.8.5"
rusttype = "0.9.3"
serde = {version="1.0.193", features = ["derive"]}
serde_json = "1.0.108"
